name: 'My Docker Action'
description: 'An example Docker action in Go'
inputs:
  message:
    description: 'An example input'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    MESSAGE: ${{ inputs.message }}