name: "create-branch-on-issue"
description: "Build and Push Docker Images automatically"
runs:
  using: "composite"
  steps:
    - name: Create new branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        BRANCH_NAME="issue-${ISSUE_NUMBER}"
        git checkout -b "${BRANCH_NAME}"
        git push origin "${BRANCH_NAME}"
