on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run my Docker action
        uses: kengo-k/sample-github-go-action@main
        with:
          message: 'Hello, world!'
